spring.application.name=DOSW-Library

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000

# SSL / HTTPS Configuration
server.port=8443
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=dosw-library